### ISSUE TITLE
Could we convert iTerm/OSX terminal themes somehow?

### ISSUE THREAD

**Issue by andrius** [blinksh/themes#1]
I am working outside most of time.

Because of that I need contrast white theme (black won't work even with little sun).

Default one is not good, i.e. try to ssh and start `mc`.

Themes support is amazing, and now I do want something contrast, i.e. Terminal Basic works great for me:
https://github.com/mbadolato/iTerm2-Color-Schemes
(there also a lot of nice themes for everyone's taste. Another repo: https://github.com/bahlo/iterm-colors) 

So, could we import iterm2 themes somehow?

**Comment by carloscabanero** [comment]
Hi Andrius!!

We could, but I would like to keep Blink's format separate as it is JS code, and we can do so much more stuff with it :) 

Creating a script to export them as Blink format (specially the konsole or terminator format) should be extremely easy. It might be a great way to bootstrap the themes gallery! Unfortunately I'm super busy right now with Persistent Connections, but I will see if I can find someone who is up to the task!

**Comment by carloscabanero** [comment]
You have it! Gotta say it is pretty impressive and they work great, I changed myself to Monokai everything now :)
